config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :vaccine_types
  end
  namespace :user do
    resources :vaccines, only:[:index, :show, :new, :create, :destroy] do
      resources :doses, only: [:new, :create]
    end
    resources :vaccine_types, only:[:show]
    resources :suggested_vaccines, only: [:index]
  end
  namespace :health do
    resources :users, only: [:index]
    resources :vaccines, only: [:index, :edit, :update]
  end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/suggested_vaccine.rb
class SuggestedVaccine < ApplicationRecord
  belongs_to :vaccine_type

  has_many :reccomended_doses, dependent: :destroy

  validates :vaccine_type, presence: true, uniqueness: true

  include PgSearch::Model
  pg_search_scope :search_global_vaccine,
  against: [:description],
  associated_against: {
    vaccine_type: [:name, :prevents, :composition, :indication]
  },
  using: {
    tsearch: {prefix: true}
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vaccines
  has_many :doses
  validates :cpf, presence: true
  validate :cpf_invalid

  def cpf_invalid
    return errors.add(:cpf, "cpf inválido") unless CPF.valid?(cpf)
  end

  include PgSearch::Model
    pg_search_scope :search_user,
    against: [:cpf],
    using: {
      tsearch: {prefix: true}
    }

  def age_in_months
    birth_date ? ((Time.zone.today - birth_date) / 30.437).to_i : 0
  end

end

app/controllers/health/users_controller.rb
class Health::UsersController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    if params[:query].present?
      @users = User.search_user(params[:query])
    elsif params[:query] == ""
      @users = "vazio"
    else
      @users = "sem_pesquisa"
    end
  end

  def show
  end

  def new
  end
end

app/controllers/user/doses_controller.rb
class User::DosesController < ApplicationController
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    # tem que chegar uma dose aqui
    @vaccine = Vaccine.find(params[:vaccine_id])
    @dose.vaccine = @vaccine
    if @dose.save
      redirect_to user_vaccines_path
    else
      render :new
    end
  end

  def dose_params
    params.require(:dose).permit(:date)
  end
end

app/controllers/user/suggested_vaccines_controller.rb
class User::SuggestedVaccinesController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    if params[:query].present?
      @vaccines = Vaccine.search_global_vaccine(params[:query])
                          .where(user: current_user)
                          # .joins(:vaccine_type)
                          # .order('vaccine_types.name')
      @suggested_vaccines = SuggestedVaccine.search_global_vaccine(params[:query])
                                            # .joins(:vaccine_type)
                                            # .order('vaccine_types.name')
    else
      @vaccines = Vaccine.where(user: current_user)
                         # .joins(:vaccine_type)
                         # .order('vaccine_types.name')
      @suggested_vaccines = SuggestedVaccine.all
                                            .joins(:vaccine_type)
                                            .order('vaccine_types.name')
    end
  end
end

app/controllers/user/vaccines_controller.rb
class User::VaccinesController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    @suggested_vaccines = SuggestedVaccine.all
    if params[:query].present?
      @vaccines = Vaccine.search_global_vaccine(params[:query]).where(user: current_user)
    else
      @vaccines = Vaccine.where(user: current_user).joins(:vaccine_type).order('vaccine_types.name')
    end
  end

  def show
    @vaccine = Vaccine.find(params[:id])
  end

  def new
    @vaccine = Vaccine.new
    @dose = Dose.new
  end

  def create
    @vaccine = Vaccine.new(vaccine_params)
    @dose = Dose.new(dose_params)
    @vaccine.user = current_user
    @dose.vaccine = @vaccine
    # criar a primeira dose
    if @vaccine.valid? && @dose.valid?
      @vaccine.save
      @dose.save
      redirect_to user_vaccines_path, notice: 'Vacina cadastrada com sucesso.'
    else
      render :new
    end
  end

  def vaccine_params
    params.require(:vaccine).permit(:vaccine_type_id)
  end

  def dose_params
    params.require(:vaccine).require(:dose).permit(:date)
  end

  def destroy
    @vaccine = Vaccine.find(params[:id])
    # Caso não use o pundit
    if @vaccine.user != current_user
      # || @vaccine.valid_doses?
      redirect_to user_vaccines_path, alert: 'Não autorizado.'
      return
    end

    @vaccine.destroy
    redirect_to user_vaccines_path, notice: 'Vacina excluida com sucesso.'
  end
end

app/views/user/suggested_vaccines/index.html.erb
<div class="container-fluid">

  <%# inicio das sugestoes de doses %>
  <div id="calendario-sus">
   <h1 class='text-center my-4' ><%= "Carteira da Recomendada do SUS" %></h1>
    <div class="search_vaccine mb-5">
      <%= form_tag user_suggested_vaccines_path, method: :get do %>
        <div class="d-flex" style="width: 80%; margin:0 auto;">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            style: "width: 80%",
            placeholder: "Procure por uma vacina em sua carteira"
          %>
          <%= submit_tag "Pesquisar", class: "br-button ml-2", primary:"" %>
        </div>
      <% end %>
    </div>
    <% if @suggested_vaccines.present? %>
      <% @suggested_vaccines.each do |suggested_vaccine| %>
        <div class="wrapper">
          <div class="vaccine-card">
            <div class="card-info">
              <div class="card-title">
                <%= suggested_vaccine.vaccine_type.name %>
              </div>
              <div class="card-description">
                Esquema: <%= suggested_vaccine.description %> | Última dose tomada: <%= @vaccines.find_by(vaccine_type: suggested_vaccine.vaccine_type).last_dose_date if @vaccines.find_by(vaccine_type: suggested_vaccine.vaccine_type).present? %>
              </div>
            </div>
            <div class="card-actions">
                <%#= link_to user_vaccine_path(vaccine), class: 'br-button' do %>
                  <%# <i class="fas fa-edit"></i>
                  Detalhes %>
                <%# end %>
                <%#= link_to user_vaccine_path(vaccine), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'br-button' do %>
                  <%# <i class="fas fa-eraser"></i> %>
                  <%# Delete %>
                <%# end %>
            </div>
          </div>
          <% suggested_vaccine.reccomended_doses.each_with_index do |sdose, index| %>
            <div class="dose-card reccomended-card">
              <% if  (@vaccines.where(vaccine_type: suggested_vaccine.vaccine_type).present?) &&
              (@vaccines.where(vaccine_type: suggested_vaccine.vaccine_type)[0].doses.count > index) %>
                <div class="card-title text-center">
                  <p>Dose <%= index + 1 %>
                  <i class="fas fa-check-circle" style="color: #45f266; display:inline-block;"></i>
                  </p>
                </div>
                <div class="card-description text-center">
                  Idade Recomendada
                  <br>
                  <%= sdose.month_age %> meses
                  <div style="color: #45f266">
                    Dose Em Dia
                  </div>
                </div>
              <% elsif current_user.age_in_months > sdose.month_age %>
                <div class="card-title text-center">
                  <p>Dose <%= index + 1 %>
                  <i class="fas fa-times-circle" style="color: red; display:inline-block;"></i>
                  </p>
                </div>
                <div class="card-description text-center">
                  Idade Recomendada
                  <br>
                  <%= sdose.month_age %> meses
                  <div style="color: red">
                    <strong>Dose Em Atraso</strong>
                  </div>
                </div>
              <% else %>
                <div class="card-title text-center">
                  <p>Dose <%= index + 1 %></p>
                </div>
                <div class="card-description text-center">
                  Idade Recomendada
                  <br>
                  <%= sdose.month_age %> meses
                  <div style="color: orange">
                    Dose Futura em <%= sdose.month_age - current_user.age_in_months %> meses
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p class="sem-vacina">Vacina não encontrada.</p>
    <% end %>
    <div class="text-right">
      <!-- Ideia de colocar esse botão como fixado na tela -->
      <%= link_to "Nova Vacina", new_user_vaccine_path, class: 'br-button my-4', action:'' %>
      <!-- , data:{ toggle:"popover" trigger:"hover" content:"Some content"} -->
    </div>
  </div>
  <%# fim das sugestoes de doses%>
</div>