config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :vaccine_types
  end
  namespace :user do
    resources :vaccines, only:[:index, :show, :new, :create, :destroy] do
      resources :doses, only: [:new, :create]
    end
    resources :vaccine_types, only:[:show]
    resources :suggested_vaccines, only: [:index]
  end
  namespace :health do
    resources :users, only: [:index]
    resources :vaccines, only: [:index, :edit, :update]
  end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vaccines
  has_many :doses
  validates :cpf, presence: true
  validate :cpf_invalid

  def cpf_invalid
    return errors.add(:cpf, "cpf inválido") unless CPF.valid?(cpf)
  end

  include PgSearch::Model
    pg_search_scope :search_user,
    against: [:cpf],
    using: {
      tsearch: {prefix: true}
    }

  def age_in_months
    birth_date ? ((Time.zone.today - birth_date) / 30.437).to_i : 0
  end

end

app/controllers/health/users_controller.rb
class Health::UsersController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    if params[:query].present?
      @users = User.search_user(params[:query])
    elsif params[:query] == ""
      @users = "vazio"
    else
      @users = "sem_pesquisa"
    end
  end

  def show
  end

  def new
  end
end

app/controllers/health/vaccines_controller.rb
class Health::VaccinesController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    @user = User.find(params[:user_id])
    @vaccines = Vaccine.where(user_id: params[:user_id]).joins(:vaccine_type).order('vaccine_types.name')
  end

  def edit
    @vaccine = Vaccine.find(params[:id])
    @doses = @vaccine.doses.order(:date).reject { |dose| dose.user.present? }
  end

  def update
    @doses = Dose.find(doses_params[:id])
    @doses.each do |dose|
      dose.update(user: current_user)
    end
    redirect_to health_vaccines_path(user_id: @doses.first.vaccine.user.id)
  end

  def doses_params
    params.require(:vaccine).require(:dose_ids).permit(id: [])
  end
end

app/controllers/user/doses_controller.rb
class User::DosesController < ApplicationController
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    # tem que chegar uma dose aqui
    @vaccine = Vaccine.find(params[:vaccine_id])
    @dose.vaccine = @vaccine
    if @dose.save
      redirect_to user_vaccines_path
    else
      render :new
    end
  end

  def dose_params
    params.require(:dose).permit(:date)
  end
end

app/controllers/user/suggested_vaccines_controller.rb
class User::SuggestedVaccinesController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    if params[:query].present?
      @vaccines = Vaccine.search_global_vaccine(params[:query])
                          .where(user: current_user)
                          # .joins(:vaccine_type)
                          # .order('vaccine_types.name')
      @suggested_vaccines = SuggestedVaccine.search_global_vaccine(params[:query])
                                            # .joins(:vaccine_type)
                                            # .order('vaccine_types.name')
    else
      @vaccines = Vaccine.where(user: current_user)
                         # .joins(:vaccine_type)
                         # .order('vaccine_types.name')
      @suggested_vaccines = SuggestedVaccine.all
                                            .joins(:vaccine_type)
                                            .order('vaccine_types.name')
    end
  end
end

app/controllers/user/vaccines_controller.rb
class User::VaccinesController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    @suggested_vaccines = SuggestedVaccine.all
    if params[:query].present?
      @vaccines = Vaccine.search_global_vaccine(params[:query]).where(user: current_user)
    else
      @vaccines = Vaccine.where(user: current_user).joins(:vaccine_type).order('vaccine_types.name')
    end
  end

  def show
    @vaccine = Vaccine.find(params[:id])
  end

  def new
    @vaccine = Vaccine.new
    @dose = Dose.new
  end

  def create
    @vaccine = Vaccine.new(vaccine_params)
    @dose = Dose.new(dose_params)
    @vaccine.user = current_user
    @dose.vaccine = @vaccine
    # criar a primeira dose
    if @vaccine.valid? && @dose.valid?
      @vaccine.save
      @dose.save
      redirect_to user_vaccines_path, notice: 'Vacina cadastrada com sucesso.'
    else
      render :new
    end
  end

  def vaccine_params
    params.require(:vaccine).permit(:vaccine_type_id)
  end

  def dose_params
    params.require(:vaccine).require(:dose).permit(:date)
  end

  def destroy
    @vaccine = Vaccine.find(params[:id])
    # Caso não use o pundit
    if @vaccine.user != current_user
      # || @vaccine.valid_doses?
      redirect_to user_vaccines_path, alert: 'Não autorizado.'
      return
    end

    @vaccine.destroy
    redirect_to user_vaccines_path, notice: 'Vacina excluida com sucesso.'
  end
end

app/views/health/users/index.html.erb
<div class="container-sm">
  <h2 class='text-center my-4' ><%= "Busca pelo Cidadão" %> </h2>

  <div class="search_vaccine">
    <%= form_tag health_users_path, method: :get do %>
    <div class="d-flex" style="width: 80%; margin:0 auto;">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        style: "width: 80%",
        placeholder: "Digite o CPF do cidadão Brasileiro ou Estrangeiro: "
      %>
      <%= submit_tag "Pesquisar", class: "btn btn-primary m-auto" %>
    </div>
    <% end %>
  </div>

<!--     <h3> SE CPF FOR VAZIO RETORNA ALERTA</h3>
    <h3> SENÃO RETORNA O CIDADÃO </h3>
    <h4> Implementar link de Acesso para show </h4> -->

    <% if @users == "vazio" %>
      <h3 class="text-center" ><strong> <%= "Digite um CPF Válido" %> </strong></h3>
    <% elsif @users == "sem_pesquisa" %>
    <% else %>
      <% @users.each do |user| %>
        <div class="wrapper">
          <div class="vaccine-card">
            <div class="card-info">
              <div class="card-title">
                Nome: <%= link_to "#{user.first_name}", health_vaccines_path(user_id: user.id) %> <%= user.last_name %>
              </div>
              <div class="card-description">
                <p> CPF: <%= user.cpf %> </p>
                <p> Endereço: <%= user.address %> </p>
                <p> Email: <%= user.email %> </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
</div>