config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :vaccine_types
  end
  namespace :user do
    resources :vaccines, only:[:index, :show, :new, :create, :destroy] do
      resources :doses, only: [:new, :create]
    end
    resources :vaccine_types, only:[:show]
    resources :suggested_vaccines, only: [:index]
  end
  namespace :health do
    resources :users, only: [:index]
    resources :vaccines, only: [:index, :edit, :update]
  end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vaccine.rb
class Vaccine < ApplicationRecord
  belongs_to :user
  belongs_to :vaccine_type
  has_many :doses, dependent: :destroy
  has_many :users, through: :doses

  # esse validador não está correto, pois queremos que uma vaccine_type seja única para um mesmo user, não para todas vaccines. por isso o scope.
  # validates :vaccine_type, uniqueness: true
  validates :vaccine_type, uniqueness: { scope: :user}

  include PgSearch::Model
  pg_search_scope :search_global_vaccine,
  against: [:user_comment],
  associated_against: {
    vaccine_type: [:name, :prevents, :composition, :indication]
  },
  using: {
    tsearch: {prefix: true}
  }

  def last_dose_date
    doses ? doses.order(:date).last.date.strftime("%d/%m/%Y") : "-"
  end

  def dose_count
    doses ? doses.count : 0
  end

  def valid_doses?
    users.count.positive? ? true : false
  end

  def comment
    user_comment ? user_comment : "Sem comentários por enqaunto."
  end

  def all_doses_valid?
    doses.count == users.count ? true : false
  end
end

app/models/vaccine_type.rb
class VaccineType < ApplicationRecord
  has_many :vaccines, dependent: :destroy
  has_many :campaigns, dependent: :destroy
  has_many :suggested_vaccines, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  include PgSearch::Model
  pg_search_scope :search_by_name_others,
  against: [:name, :prevents, :composition, :indication],
  using: {
    tsearch: {prefix: true}
  }
end

app/controllers/health/users_controller.rb
class Health::UsersController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    if params[:query].present?
      @users = User.search_user(params[:query])
    elsif params[:query] == ""
      @users = "vazio"
    else
      @users = "sem_pesquisa"
    end
  end

  def show
  end

  def new
  end
end

app/controllers/health/vaccines_controller.rb
class Health::VaccinesController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    @user = User.find(params[:user_id])
    @vaccines = Vaccine.where(user_id: params[:user_id]).joins(:vaccine_type).order('vaccine_types.name')
  end

  def edit
    @vaccine = Vaccine.find(params[:id])
    @doses = @vaccine.doses.order(:date).reject { |dose| dose.user.present? }
  end

  def update
    @doses = Dose.find(doses_params[:id])
    @doses.each do |dose|
      dose.update(user: current_user)
    end
    redirect_to health_vaccines_path(user_id: @doses.first.vaccine.user.id)
  end

  def doses_params
    params.require(:vaccine).require(:dose_ids).permit(id: [])
  end
end

app/controllers/user/vaccines_controller.rb
class User::VaccinesController < ApplicationController
  def index
    # Colocar os ifs pra dar redirect caso não seja um citzen
    @suggested_vaccines = SuggestedVaccine.all
    if params[:query].present?
      @vaccines = Vaccine.search_global_vaccine(params[:query]).where(user: current_user)
    else
      @vaccines = Vaccine.where(user: current_user).joins(:vaccine_type).order('vaccine_types.name')
    end
  end

  def show
    @vaccine = Vaccine.find(params[:id])
  end

  def new
    @vaccine = Vaccine.new
    @dose = Dose.new
  end

  def create
    @vaccine = Vaccine.new(vaccine_params)
    @dose = Dose.new(dose_params)
    @vaccine.user = current_user
    @dose.vaccine = @vaccine
    # criar a primeira dose
    if @vaccine.valid? && @dose.valid?
      @vaccine.save
      @dose.save
      redirect_to user_vaccines_path, notice: 'Vacina cadastrada com sucesso.'
    else
      render :new
    end
  end

  def vaccine_params
    params.require(:vaccine).permit(:vaccine_type_id)
  end

  def dose_params
    params.require(:vaccine).require(:dose).permit(:date)
  end

  def destroy
    @vaccine = Vaccine.find(params[:id])
    # Caso não use o pundit
    if @vaccine.user != current_user
      # || @vaccine.valid_doses?
      redirect_to user_vaccines_path, alert: 'Não autorizado.'
      return
    end

    @vaccine.destroy
    redirect_to user_vaccines_path, notice: 'Vacina excluida com sucesso.'
  end
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
  def to_currency(float)
    sprintf('R$ %.2f', float).gsub('.', ',')
  end
end

app/views/health/vaccines/edit.html.erb
<div class="mx-auto w-25">
  <%= simple_form_for(@vaccine, url: health_vaccine_path, html: { class: "text-center" }) do |f| %>
    <%= f.simple_fields_for :dose_ids do |dose_form| %>
      <% @doses.each_with_index do |dose, index| %>
        <div class="dose-card" style="position:relative;">
          <div class="card-title text-center">
            <p>
              Dose <%= index + 1 %>
            </p>
          </div>
          <div class="card-description text-center">
            <%= dose.date.strftime("%d/%m/%Y") %>
          </div>
          <div id="gambiarradoandrezao" style="position: absolute; top:8px;left:8px;">
            <%= dose_form.input :id,
                                collection: [dose],
                                label: "",
                                required: false,
                                include_hidden: false,
                                as: :check_boxes  %>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= f.submit "Validar", class: "br-button mt-3", primary:"", data: { confirm: 'Tem certeza que deseja Autenticar?' }%>
  <% end %>
</div>

app/views/health/vaccines/index.html.erb
<div class="container-sm">
  <h1 class='text-center my-4' ><%= "Carteira de Vacinação de #{@user.first_name}" %></h1>

  <% if @vaccines.present? %>
    <% @vaccines.each do |vaccine| %>
      <div class="wrapper">
        <div class="vaccine-card">
          <div class="card-info">
            <div class="card-title">
              <%= vaccine.vaccine_type.name %>
            </div>
            <div class="card-description">
              Doses Tomadas: <%= vaccine.dose_count %> | Última dose: <%= vaccine.last_dose_date %>
            </div>
          </div>
          <div class="card-actions">
              <%= link_to root_path, class: 'br-button' do %>
                <i class="fas fa-edit"></i>
                Detalhes
              <% end %>
              <% unless vaccine.all_doses_valid? %>
                <%= link_to edit_health_vaccine_path(vaccine), class: 'br-button' do %>
                  <i class="fas fa-check"></i>
                  Autenticar
                <% end %>
              <% end %>
          </div>
        </div>
        <% vaccine.doses.order(:date).each_with_index do |dose, index| %>
          <div class="dose-card">
            <div class="card-title text-center">
              <p>
                Dose <%= index + 1 %>
                <% if dose.user %>
                 <i class="fas fa-check-circle" style="color: #45f266; display:inline-block;"></i>
                <% end %>
              </p>
            </div>
            <div class="card-description text-center">
              <%= dose.date.strftime("%d/%m/%Y") %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p class="sem-vacina">Sem vacinas por enquanto</p>
  <% end %>
</div>