config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :vaccine_types
  end
  namespace :user do
    resources :vaccines, only:[:index, :show, :new, :create, :destroy] do
      resources :doses, only: [:new, :create]
    end
    resources :vaccine_types, only:[:show]
    resources :suggested_vaccines, only: [:index]
  end
  namespace :health do
    resources :users, only: [:index]
    resources :vaccines, only: [:index, :edit, :update]
  end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="br-footer" style="height=10vh">
  <div class="container-lg">
    
    
    <div class="d-none d-sm-block">
      <div class="row align-items-end justify-content-between">
        <div class="col social-network">
          <p class="text-up-01 text-extra-bold text-uppercase mb-0 mt-2" style="font-size:15px" >Redes Sociais</p>
          <i class="fab fa-linkedin-in fa-1x"></i>
           <i class="fab fa-twitter fa-1x"></i>
           <i class="fab fa-facebook-f fa-1x"></i>
           <i class="fab fa-instagram fa-1x"></i>
        </div>
        <div class="logo py-1">
     <img src="https://www.gov.br/++theme++padrao_govbr/img/govbr-colorido-b.png" alt="Imagem" style="max-width: 120px;">
    </div>
        <div class="col assigns text-right">
        <%= image_tag "sus-logo-branco-h.png", class: "ml-4 mb-1", alt: "sus" %>
        </div>
      </div>
    </div>
  </div>
  <div class="br-divider"></div>
  <div class="container-lg">
    <div class="info">
      <div class="text-down-01 text-medium pb-3 text-center">Trabalho desenvolvido para fins didáticos de alunos do curso "Coding Bootcamp" da escola "LeWagon"</div>
    </div>
  </div>
</div>


 <%# <div class="logo p-0">
      <img src="https://www.gov.br/++theme++padrao_govbr/img/govbr-colorido-b.png" alt="Imagem">
    </div>
        <div class="col assigns text-right"><%= image_tag "sus-logo-branco-h.png", class: "ml-4 mb-1", alt: "sus" %>
        <%# </div>
      </div>
    </div>
  </div>
  <div class="br-divider"></div>
  <div class="container-lg">
    <div class="info">
      <div class="text-down-01 text-medium pb-3 text-center">Trabalho desenvolvido para fins didáticos de alunos do curso "Coding Bootcamp" da escola "LeWagon"</div>
    </div>
  </div> %>
<%# </div> %> 

app/views/shared/_header.html.erb
<div class="br-header" style="width: 100%; margin-bottom: 45px;">
    <div class="container-fluid d-flex justify-content-between">
        <div class="d-flex">
            <div class="logo">
                <%= image_tag "sus_logo.png", alt: "sus" %>
                <%# <div class="sign width 100%">VacinasApp</div> %>
            </div>
            <div class="menu ml-2 my-4" style="width:100%">
                <div class="title mt-1" style="font-size: 20px">Carteira de Vacinação Digital</div>
                <div class="subtitle mb-2 text-left ml-0">Sempre em dia com a sua saúde</div>
            </div>
        </div>
        <div>
            <div class="actions mt-4" style="max-width:100%">
                <div class="links">
                    <button class="br-button" type="button" circle mini>
                        <i class="fas fa-ellipsis-v"></i>
                    </button>
                    <% if current_user && current_user.role == "Cidadão" %>
                      <ul>
                          <!-- <li class="title">Acesso Rápido</li> -->
                          <li> <%= link_to "Sua Carteira", user_vaccines_path, id:"toggle-btn"%> </li>
                          <li> <%= link_to "Calendário de Vacinação", user_suggested_vaccines_path, id:"toggle-btn2"%></li>
                          <li><a href="https://antigo.saude.gov.br/saude-de-a-z/vacinacao/campanhas" target=_blank>Campanhas Vigentes</a></li>
                      </ul>
                    <% end %>
                </div>

                <div class="search-btn">
                    <button class="br-button" type="button" circle mini>
                        <i class="fas fa-search"></i>
                    </button>
                </div>
                <% if current_user.nil? %>
                <div class="login">
                    <%= link_to new_user_session_path do %>
                    <button class="br-button" type="button" mini>
                        <i class="fas fa-user"></i><span class="ml-1">Entrar</span>
                    </button>
                    <% end %>
                </div>
                <% else %>
                <div class="login">
                    <%= link_to destroy_user_session_path, method: :delete do %>
                    <button class="br-button" type="button" mini>
                        <i class="fas fa-user"></i><span class="ml-1">Sair</span>
                    </button>
                    <% end %>
                </div>
                <% end %>
                <% if !current_user.nil? %>
                <div class="avatar">
                    <div class="br-badge" danger>
                        <div class="icon">5</div>
                        <div class="content">
                              <div class="br-avatar">
                                  <div class="image">
                                      <!-- <img src="https://picsum.photos/id/823/400" alt="Avatar" /> -->
                                      <!--  -->
                                      <% if current_user.first_name == "Mia" %>
                                       <%= image_tag "a7110fab-3e67-4839-a70f-5f2c96cbc84f.jpg",
                                        class: "dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                                      <% elsif current_user.first_name == "Lourdes" %>
                                        <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1599440056/rpoze0ufujtrnzysyxpe.jpg",
                                        class: "dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                                      <% else %>
                                        <%= image_tag "https://avatars2.githubusercontent.com/u/66792796?v=4",
                                        class: "dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                                      <% end %>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                                        </div>
                                  </div>
                              </div>
                        </div>
                    </div>
                </div>
                <% end %>

            </div>
<!--             <div class="search" style="margin-left:auto">
                <div class="br-input has-icon">
                    <label></label>
                    <input class="has-icon" type="text" placeholder="Quer saber sobre alguma vacina?" />
                    <button class="icon" type="button">
                        <span class="icon"><i class="fas fa-search"></i></span>
                    </button>
                </div>
                <button class="br-button search-close" type="button" circle mini>
                    <i class="fas fa-times"></i>
                </button>
            </div> -->
        </div>
    </div>
</div>

app/views/shared/_modal_new_dose.html.erb
<div class="modal fade" id="modal-window<%=vaccine.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <%= simple_form_for(Dose.new, as: :dose, method: :post, url: user_vaccine_doses_path(vaccine)) do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Nova Dose</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :date,
                          as: :string,
                          label: "Data Dose",
                          input_html: {class: "datepicker", style: "margin: 0 !important;"},
                          order: [:day, :month, :year]
                           %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit 'Registrar Dose', class: 'br-button mr-0', primary:"" %>
          <%= link_to 'Voltar', user_vaccines_path, class: 'br-button mr-0', secondary:"" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-home <%= yield(:navbar_class) %>">
  <!-- NAVBAR CONTENT -->
</div>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand", id:"logo-home" do %>
    <%= image_tag "sus-logo-branco-hp.png" %>
  <% end %>

  <button class="navbar-toggler" style="padding:0 20px" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    
  </button>
    <div class="login">
        <%= link_to new_user_session_path do %>
        <button class="br-button login-home" type="button" mini>
            <i class="fas fa-user" style="color:white"></i><span class="ml-1" style="color:white">Entrar</span>
        </button>
        <% end %>
    </div>
</div>